### ISSUE TITLE
ctx.get is not a function

### ISSUE THREAD

**Issue by XaveScor** [XaveScor/signal-components#16]
After upgrading to v0.5.0, I have taken a regression.
Reproduce: https://codesandbox.io/p/sandbox/signal-components-simple-example-74tdrh
